apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    {{- include "app.label" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
  type: ClusterIP